# servers/reranker/parameter.yaml

model_name_or_path: openbmb/MiniCPM-Reranker-Light
backend: openai # options: infinity, sentence_transformers, openai
backend_configs:
  infinity:
    bettertransformer: false
    pooling_method: auto
    device: cuda
    model_warmup: false
    trust_remote_code: true
  sentence_transformers:
    device: cuda
    trust_remote_code: true
  openai:
    model_name: qwen3-emb-0_6b
    base_url: "http://10.65.8.100:17000/v1"
    api_key: 

gpu_ids: 0
top_k: 5
batch_size: 16
query_instruction: ""
